# your name (or website title) here
title: Heidi TM

# your photo (or logo) here
logo: "/images/profile pic - circle.jpg"

# your text below (remove <br> elements if you don't need line breaks)
description: > 
  Hi! I am an Analyst interested in data science and machine learning. 
   
  <br><br><b>Analytics & Research Experience in:</b> Digital Marketing (B2B), Consumer Insights and Market Research/Consulting
  <br><br><b>Skills:</b> Python, R, SQL, Power BI, Tableau, HTML, CSS
  <br><br><b>IDE:</b> Jupyter Notebook, RStudio
  
  <br><br>
  
  <a href=https://linkedin.com/in/heidi-885322150>LinkedIn|</a>
  <a href=https://angel.co/u/h-t-6>AngelList|</a>
  <a href=https://public.tableau.com/app/profile/heidi.tm#!/>Tableau|</a>
  <a href=https://github.com/heiditm>Github</a> 

#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fa fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fab fab-brands fab-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fas fas-brands fas-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fab fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fas fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fa fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fab-brands fab-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fas-brands fas-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
  
#  <a href="https://linkedin.com/in/heidi-885322150" target="_blank"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150" target="_blank"><i class="fa fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href="https://linkedin.com/in/heidi-885322150" target="_blank"><i class="fa fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>

#  <a href=https://linkedin.com/in/heidi-885322150><i class="fa-brands fa-linkedin fa-2x" aria-hidden="true"></i></a>
#  <a href=https://linkedin.com/in/heidi-885322150><i class="fab-brands fab-linkedin fab-2x" aria-hidden="true"></i></a>
#  <a href=https://linkedin.com/in/heidi-885322150><i class="fas-brands fas-linkedin fas-2x" aria-hidden="true"></i></a>
  

#  <a href=mailto:test@gmail.com><i class="fa-envelope"></i></a>
#  <a href=https://linkedin.com/in/heidi-885322150><i class="fa-linkedin"></i></a>
#  <a href=https://public.tableau.com/app/profile/heidi.tm#!/> <i class="fa-asterisk"></i></a>
#  <a href=https://github.com/heiditm> <i class="fa-github"></i></a>
  
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
